kind: MCPInvoke
apiVersion: api.ibm.com/v1
metadata:
  name: mcp-invoke-3adnq
  namespace: MyTestGit
  version: 1.0.0
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  input: request
  endpoint:
    httpSse:
      serverUrl:
        plain:
          value: https://calculator.caseyjhand.com/mcp
      timeout: 30
      tlsClientProfile: sample-tls-client-profile:1.0.0
    primitive:
      tool:
        name:
          plain:
            value: tool_name
        output: response
