kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: policy-sequence-3adnq
  namespace: MyTestGit
  version: 1.0.0
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  main:
    - $ref: MyTestGit:mcp-invoke-3adnq:1.0.0
  monitoring:
    $ref: MyTestGit:telemetry-3adnq:1.0.0
