kind: Quota
apiVersion: api.ibm.com/v1
metadata:
  name: quota-3adnq
  namespace: MyTestGit
  version: 1.0.0
  tags: []
spec:
  maxRequest: 1000
  interval: 1m
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        exceedAction: return429
